### ISSUE TITLE
use createSymlink: true

### ISSUE THREAD

**Issue by alitvm** [winstonjs/winston-daily-rotate-file#259] opened 2019-12-23 02:14 UTC
Error: EPERM: operation not permitted, symlink 'default-2019-12-23.log' -> 'data\logs\tc_admin_server/default.log'
      at Object.symlinkSync (fs.js:935:3)
      at createCurrentSymLink (\git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:303:16)
      at EventEmitter.<anonymous> (\git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:530:17)
      at EventEmitter.emit (events.js:205:15)
      at \git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:607:20
      at processTicksAndRejections (internal/process/task_queues.js:82:9) {
    errno: -4048,
    syscall: 'symlink',
    code: 'EPERM',
    path: 'default-2019-12-23.log',
    dest: 'data\\logs\\tc_admin_server/default.log'

**Comment by alitvm** [comment] 2019-12-23 02:16
use admin  pm2 start ecosystem.config.js   error

**Comment by alitvm** [comment] 2019-12-23 03:01
at Object.<anonymous> (\git_project\server\utils\logger.js:24:27)
     at Module._compile (internal/modules/cjs/loader.js:774:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
      at Module.load (internal/modules/cjs/loader.js:641:32)
  Error: EPERM: operation not permitted, symlink 'default-2019-12-23.log' -> 'data\logs\server\1\19164/default.log'
      at Object.symlinkSync (fs.js:935:3)
      at createCurrentSymLink (\git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:303:16)
      at EventEmitter.<anonymous> (\git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:530:17)
      at EventEmitter.emit (events.js:200:13)
      at Object.FileStreamRotator.getStream (\git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:609:16)
      at new DailyRotateFile (\git_project\server\node_modules\winston-daily-rotate-file\daily-rotate-file.js:80:57)
      at Object.<anonymous> (\git_project\server\utils\logger.js:24:27)
      at Module._compile (internal/modules/cjs/loader.js:774:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
      at Module.load (internal/modules/cjs/loader.js:641:32)




      at Object.<anonymous> (\git_project\server\utils\logger.js:24:27)
      at Module._compile (internal/modules/cjs/loader.js:774:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
      at Module.load (internal/modules/cjs/loader.js:641:32)
  Error: EPERM: operation not permitted, symlink 'default-2019-12-23.log' -> 'data\logs\server\0\1952/default.log'
      at Object.symlinkSync (fs.js:935:3)
      at createCurrentSymLink (\git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:303:16)
      at EventEmitter.<anonymous> (\git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:530:17)
      at EventEmitter.emit (events.js:200:13)
      at Object.FileStreamRotator.getStream (\git_project\server\node_modules\file-stream-rotator\FileStreamRotator.js:609:16)
      at new DailyRotateFile (\git_project\server\node_modules\winston-daily-rotate-file\daily-rotate-file.js:80:57)
      at Object.<anonymous> (\git_project\server\utils\logger.js:24:27)
      at Module._compile (internal/modules/cjs/loader.js:774:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
      at Module.load (internal/modules/cjs/loader.js:641:32)

**Comment by mattberther** [comment] 2019-12-27 19:05
This seems to be a dupe of #226. Working in a process manager seems to cause some problems and we're working on identifying a fix.

**Closed by mattberther** 2019-12-27 19:05 UTC
