### ISSUE TITLE
Sometimes the rotator doesn't zip the log file

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [winstonjs/winston-daily-rotate-file#288] opened 2020-08-07 01:33 UTC
Using a configuration to zip when file size is more than 1k for example, some files are zipped when rotated, but some files don't.

```javascript
winston.loggers.add('category1', {
  format: combine(
    simple(),
    timestamp()
  ),
  transports: [
    new winston.transports.Console({ level: 'debug' }),
    new DailyRotateFile({
      filename: 'logs/application-%DATE%.log',
      datePattern: 'YYYY-MM-DD-HH',
      zippedArchive: true,
      maxSize: '1k',
      maxFiles: '14d'
    })
  ]
});
```

File `application-2020-08-06-22.log.2` wasn't zipped

![winston-rotate-logs-zip](https://user-images.githubusercontent.com/32627919/89598879-5a1d7380-d834-11ea-9c37-a64d9c40f4a2.png)

**Comment by mattberther** [comment] 2020-08-09 19:51
Monitoring the upstream PR and will merge/resolve this when it's merged there.

**Comment by srishti-monali** [comment] 2020-09-19 11:40
Using this configuration
```javascript
const infoTransport = new (winston.transports.DailyRotateFile)({
  level: 'info',
  filename: 'logs/application-%DATE%.log',
  datePattern: 'YYYY-MM-DD',
  zippedArchive: true,
  createSymlink: true
});

const errorTransport = new (winston.transports.DailyRotateFile)({
  level: 'error',
  filename: 'logs/error-%DATE%.log',
  datePattern: 'YYYY-MM-DD',
  zippedArchive: true
});
```

**Problem**: It archives all `application-date.log` except a few, which gets missed(may be because of service restart).
**BUT**, it does not archive any `error-date.log` file. 

Am I missing anything in the **configuration**? Thanks for any help in Advance.

**Comment by mattberther** [comment] 2020-10-01 23:41
@srishti-monali I'm unable to reproduce your problem with the configuration you provided. Without further understanding of what you're doing, I could only speculate. However, please note that archival or rotation doesn't happen until the transport is used, so if you're not sending a log with an error level, it would not rotate.

If this continues to be an issue, would you please provide the smallest code that accurately reproduces the issue you're seeing?

**Comment by mattberther** [comment] 2021-02-01 18:51
Closing due to non-response.

**Closed by mattberther** 2021-02-01 18:51 UTC
Labels: waiting
