### ISSUE TITLE
deprecated dependencies...

### ISSUE THREAD

**Issue by vkynchev** [winstonjs/winston-daily-rotate-file#134] opened 2018-04-11 11:26 UTC
Is anyone else getting these warnings?
I'm using node v9.5.0...
```
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
```

**Comment by douira** [comment] 2018-04-14 18:03
I'm also getting these warnings. They originate from the package winston-compat 0.1.0 which requires vows 0.8.1 which requires glob 4.0.6 (old) which requires a bunch of outdated packages that make those warnings. The solutions seems to be to simply remove or properly update winston-compat to use newer packages.

**Comment by mattberther** [comment] 2018-04-17 19:05
This has been documented at https://github.com/winstonjs/winston-compat/issues/4. I'll close this issue once the issue is resolved over there.

**Comment by mattberther** [comment] 2018-04-23 20:43
This should be resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/1d09b2b8d56794e4dc67b5ead5aa5c4a92124412. Pushed to npm as `winston-daily-rotate-file@3.1.3`.

**Closed by mattberther** 2018-04-23 20:43 UTC
