### ISSUE TITLE
TypeError: winston.transports.DailyRotateFile is not a constructor

### ISSUE THREAD

**Issue by nengine** [winstonjs/winston-daily-rotate-file#96] opened 2017-10-10 12:12 UTC
I am not sure what I'm doing wrong here. Any help is appreciated.

```js
var winston = require('winston');
require('winston-daily-rotate-file');

var transport = new (winston.transports.DailyRotateFile)({
	filename: './application.log',
	datePattern: 'yyyy-MM-dd.',
	prepend: true,
	level: process.env.ENV === 'development' ? 'debug' : 'info'
});

const logger = winston.createLogger({
  level: 'info',
  format: format.combine(
  	format.timestamp(),
  	logFormat
  ),
    
  transports: [
    //
    // - Write to all logs with level `info` and below to `combined.log` 
    // - Write all logs error (and below) to `error.log`.
    //
    new winston.transports.File({ filename: 'error.log', level: 'error' }),
    transport
  ]
});
```
error output
```js
var transport = new (winston.transports.DailyRotateFile)({
                ^

TypeError: winston.transports.DailyRotateFile is not a constructor
    at Object.<anonymous> (C:\Users\nash\wsclient\app.js:32:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by mattberther** [comment] 2017-10-11 01:43
@nengine Do you have some information on the environment you're using? What's your node version, winston version, and winston-daily-rotate-file version?

**Comment by nengine** [comment] 2017-10-11 12:19
Hi, node v6.6.0 and winston@3.0.0-rc0 with winston-daily-rotate-file 1.7.2.  Thanks.

**Comment by nengine** [comment] 2017-10-11 20:12
I got it working by changing the code like shown below.  Custom log format was not applied in the daily log file, but it seems to be fine in regular log file.  Is there anyway to get custom log format to be hooked into daily log file?


```js
const winston = require('winston');
const DailyRotateFile = require('winston-daily-rotate-file');
const { format } = require('logform');

const logger = winston.createLogger({
  level: 'info',
  format: format.combine(
  	format.timestamp(),
  	logFormat
  ),
    
  transports: [

    new winston.transports.File({ filename: 'error.log', level: 'error' }),
    new winston.transports.File({ filename: 'application.log' }),
    new DailyRotateFile({
		  filename: './log',
		  datePattern: 'yyyy-MM-dd.',
		  prepend: true,
		  localTime: true,
		  level: process.env.NODE_ENV === 'development' ? 'debug' : 'info'
		})
  ]
});
```

2017-10-11.log output
```txt
{"message":"MySQL server connection establised.","level":"info","timestamp":"2017-10-11T20:06:24.371Z"}
{"message":"executed Heartbeat.sync() in mysqldb","level":"info","timestamp":"2017-10-11T20:06:24.422Z"}
{"message":"executed Ticker.sync() in mysqldb","level":"info","timestamp":"2017-10-11T20:06:24.425Z"}
{"message":"executed Fill.sync() in mysqldb","level":"info","timestamp":"2017-10-11T20:06:24.426Z"}
```

application.log output
```txt
[2017-10-11T20:06:24.368Z] info: MySQL server connection establised.
[2017-10-11T20:06:24.422Z] info: executed Heartbeat.sync() in mysqldb
[2017-10-11T20:06:24.425Z] info: executed Ticker.sync() in mysqldb
[2017-10-11T20:06:24.426Z] info: executed Fill.sync() in mysqldb
```

**Comment by mattberther** [comment] 2017-10-13 16:10
@nengine There appears to have been some breaking changes in the winston 3.0 library. I'll look to make appropriate adjustments to support it. Meanwhile, regarding your format question, are you able to add the format property to the DailyRotateFile options?

```
    new DailyRotateFile({
		  filename: './log',
		  datePattern: 'yyyy-MM-dd.',
		  prepend: true,
		  localTime: true,
		  level: process.env.NODE_ENV === 'development' ? 'debug' : 'info',
                  format: // your custom format code here
		})

**Comment by nengine** [comment] 2017-10-13 16:14
Hi Thanks! No for some reason format is still not working.  Do I need to apply custom format for DailyRotateFile options?  For regular winston.transports.File it just works when it is defined at the logger level.

**Comment by mattberther** [comment] 2017-10-13 16:18
Im sorry. `formatter` option, which says: If function is specified, its return value will be used instead of default output. (default undefined)

I know this was how it was done with winston 2.x. Again, I'll be looking to make appropriate changes to support 3.x.

**Comment by mattberther** [comment] 2017-11-05 22:49
Closing this issue as dupe of @#106. Please track the progress of winston 3.0 compatibility there.

**Closed by mattberther** 2017-11-05 22:49 UTC
