### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/somepath/some-api.log.2018-10-24'

### ISSUE THREAD

**Issue by devingao-df** [winstonjs/winston-daily-rotate-file#191] opened 2018-11-08 01:02 UTC
The error broke the app. It was trying to access a file 14 days ago. 

    "winston": "^2.3.1",
    "winston-daily-rotate-file": "^3.3.0",

let params = {
  filename: "/somepath/some-api.log",
  level: level,
  maxDays: 14,
  zippedArchive: true,
  timestamp: true,
  json: true
};

**Comment by ankitcf** [comment] 2018-11-12 02:52
Seems to be duplicate of [https://github.com/winstonjs/winston-daily-rotate-file/issues/174](174). its fixed in 3.3.4

**Comment by mattberther** [comment] 2019-01-14 02:57
Closing to non-response. If this continue to be an issue, please re-open and provide a small code sample that reproduces the problem.

**Closed by mattberther** 2019-01-14 02:57 UTC
