### ISSUE TITLE
Wrong default path for audit folder for code compiled on Windows PC, running in docker container

### ISSUE THREAD

**Issue by stefaanMLB** [winstonjs/winston-daily-rotate-file#258] opened 2019-12-16 15:04 UTC
Development environment: **Windows10 64bit + vscode**
typescript: **v3.7.2**
node version: **v10.15.3**
Winston version: **^3.2.1**
winston-daily-rotate-file version: **^4.3.0**

Daily-transport configuration 
```javascript
let drTransport = new DailyRotateFile({
   level: 'info',
   frequency: '24h',
   dirname: loggingDir,
   filename: `${appName}-%DATE%.log`,
   datePattern: 'YYYY-MM-DD',
   maxFiles: 14,
   handleExceptions: false,
   json: true,
   format: winston.format.combine(
      winston.format(info => { 
         info.namespace = appName + '.' + info.namespace;
         return info; 
      })(),
      winston.format.timestamp(),
      winston.format.json()
   )
});
```
Code runs fine in development (transpiled on Windows, run on Windows, no dockerization)
When transpiled on windows, dockerized on Windows and run either on Windows or Linux I get this error message
```
2019-12-16T14:42:31.855Z '[FileStreamRotator] Failed to store log audit at:' 'logs\\.6a038f5c781cc559461411166b733f5dd227ead1-audit.json' 'Error:' { Error: EACCES: permission denied, open 'logs\.6a038f5c781cc559461411166b733f5dd227ead1-audit.json'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at Object.FileStreamRotator.writeAuditLog (/usr/bruyland/node_modules/file-stream-rotator/FileStreamRotator.js:259:12)
    at Object.FileStreamRotator.addLogToAudit (/usr/bruyland/node_modules/file-stream-rotator/FileStreamRotator.js:389:27)
    at EventEmitter.<anonymous> (/usr/bruyland/node_modules/file-stream-rotator/FileStreamRotator.js:528:36)
    at EventEmitter.emit (events.js:189:13)
    at Object.FileStreamRotator.getStream (/usr/bruyland/node_modules/file-stream-rotator/FileStreamRotator.js:609:16)
    at new DailyRotateFile (/usr/bruyland/node_modules/winston-daily-rotate-file/daily-rotate-file.js:80:57)
    at Object.<anonymous> (/usr/bruyland/config/winston-config.js:35:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'logs\\.6a038f5c781cc559461411166b733f5dd227ead1-audit.json' }
```
The problem are **the two back-slashes** after the `logs` folder name of the audit file..
When the same code is transpiled on Linux (docker hub autobuild) and run on Linux, the problem is not there.

Here's the Dockerfile
```dockerfile
# Global ARGs, must be defined before the first stage !
ARG AP="/usr/bruyland"
ARG BUILD_DIR="build"
ARG IMAGE_NAME
ARG BUILD_DATE
ARG GIT_COMMIT
ARG GIT_TAG
ARG SOURCE_BRANCH=bruyland/batch-processes:master

FROM node:10.15.3 as builder
ARG AP
ARG BUILD_DIR

WORKDIR ${AP}
COPY . .
RUN npm install
RUN npm run build-prod

FROM node:10.15.3
ARG AP
ARG BUILD_DIR
ARG IMAGE_NAME
ARG GIT_COMMIT
ARG GIT_TAG
ARG SOURCE_BRANCH

# Set the working directory
WORKDIR ${AP}

# Install Node.js dependencies
COPY --from=builder ${AP}/package.json .
COPY --from=builder ${AP}/package-lock.json .
RUN npm install --production --no-optional

# Copy application files
COPY --from=builder --chown=node:node ${AP}/${BUILD_DIR} .

RUN echo ${GIT_TAG} - ${GIT_COMMIT} > VERSION
RUN echo ${BUILD_DATE} > BUILD_DATE
RUN cat VERSION

# Change user
USER node

# Run the container under "node" user by default
CMD [ "node", "app.js" ]
```

**Comment by mattberther** [comment] 2019-12-18 03:37
This is likely an issue with the transpiler. Can you provide some information about the transpiler you're using?

**Comment by stefaanMLB** [comment] 2019-12-18 07:07
typescript v3.7.2
Actually, the file that defines the winston object is written in pure javascript, it is not transpiled.  Here's the file for reference
```js
"use strict";

const config = require('config');
const winston = require('winston');
const DailyRotateFile = require('winston-daily-rotate-file');
const fs = require('fs');

const appName = config.get('application.name');
const loggingDir = 'logs';

let drTransport = new DailyRotateFile({
   level: 'info',
   frequency: '24h',
   dirname: loggingDir,
   filename: `${appName}-%DATE%.log`,
   datePattern: 'YYYY-MM-DD',
   maxFiles: 14,
   handleExceptions: false,
   json: true,
   format: winston.format.combine(
      winston.format(info => info.namespace = appName + '.' + info.namespace)(),
      winston.format.timestamp(),
      winston.format.json()
   )
});

const myConFormat = winston.format.printf(({ level, message, label, timestamp }) => {
   return `[${level}]: ${message}`;
});

const consoleTransport = new winston.transports.Console({
   level: 'debug',
   handleExceptions: true,
   format: winston.format.combine(
      winston.format.colorize(),
      myConFormat
   )
});

const log = winston.createLogger(
      { transports: [drTransport, consoleTransport] }
);

export default log;
```

**Comment by mattberther** [comment] 2019-12-27 19:07
There is a lot in play here. Could you provide steps to reproduce using the smallest number of files possible to exclude application-specific problems (e.g., a small logger config and file that uses it and a Dockerfile that exhibits the issue)?

Thank you.

**Comment by mattberther** [comment] 2020-06-13 15:10
Closing due to non-response. If the issue persists, please re-open and provide the requested information.

**Closed by mattberther** 2020-06-13 15:10 UTC
