### ISSUE TITLE
Application crash if the file to be rotated is locked (read only) by another process

### ISSUE THREAD

**Issue by erosval** [winstonjs/winston-daily-rotate-file#178] opened 2018-09-20 21:30 UTC
When the following error happened, the application **crash**!

`Error: EBUSY: resource busy or locked, unlink 'd:\home\dev\test\prj\my-app\logs\my-app-20180920-13.log'
fs.js:1061
    at Object.fs.unlinkSync (fs.js:1061:18)
    at WriteStream.<anonymous> (d:\home\dev\test\prj\my-app\node_modules\winston-daily-rotate-file\daily-rotate-file.js:101:24)`

The solution seem so simple: use try\catch to surround `fs.unlinkSync(oldFile);` on [daily-rotate-file.js](https://github.com/winstonjs/winston-daily-rotate-file/blob/master/daily-rotate-file.js#L101)

You can find a similar solution at [FileStreamRotator.js](https://github.com/rogerc/file-stream-rotator/blob/master/FileStreamRotator.js#L262)

**Comment by mattberther** [comment] 2018-09-22 14:48
This appears to be a dupe of #174. Please reopen if that is not the case.

**Closed by mattberther** 2018-09-22 14:48 UTC
