### ISSUE TITLE
Errors dont get logged to daily rotated logfile

### ISSUE THREAD

**Issue by dasAnderl** [winstonjs/winston-daily-rotate-file#160] opened 2018-06-14 22:07 UTC
errors passed as meta (log.error('error', new Error('Error object should be logged'))) do not appear in the logfile (daily rotation). in the console they appear.

```
"winston": "^2.4.2",
"winston-daily-rotate-file": "^3.1.4"
```

see my logger cfg (with a workaround)

``` javascript
import * as winston from "winston";
import {LoggerInstance} from "winston";
import {Cfg} from "./cfg";
import moment = require("moment");

export class Logger {

    private static timestamp = () => {
        return moment().format('YYYY-MM-DD HH:mm:ss:SSS');
    };

    private static formatter = (options) => {
        let metaString = Logger.getMetaString(options);
        return options.timestamp() + ' ' +
            winston.config.colorize(options.level, options.level.toUpperCase()) + ' ' +
            (options.message ? options.message : '') +
            '\n\t' + metaString;
    };

    private static getMetaString(options) {
        let meta = options.meta;
        if(!meta) {
            return '';
        }
        //Error do not get logged to daily file rotate -> special handling
        // https://github.com/winstonjs/winston/issues/610
        if( meta.stack && meta.stack.startsWith('Error')) {
            meta = { message: meta.message, stack: meta.stack};
        }
        try {
            return JSON.stringify(meta);
        } catch (e) {
            return meta.toString();
        }
    }

    private static cfg = Cfg.get();

    static init(name, fileName): LoggerInstance {

        return new winston.Logger({
            transports: [
                new (winston.transports.Console)({
                    timestamp: this.timestamp,
                    formatter: this.formatter,
                    name: name + '_console',
                    prettyPrint: true,
                    level: this.cfg.logging.console.level
                }),
                new (require('winston-daily-rotate-file'))({
                    timestamp: this.timestamp,
                    formatter: this.formatter,
                    name: name + '_file',
                    level: 'debug',
                    prettyPrint: true,
                    filename: fileName
                })
            ]
        });
    }
}

//normal logger
export const logger: LoggerInstance = Logger.init('standard-logger', './logs/trading-bot.log');
export default logger;
//logger for signals and orders
export const loggerOrder: LoggerInstance = Logger.init('orders-signals', './logs/orders-signals.log');
```

**Comment by mattberther** [comment] 2018-06-20 03:46
@dasAnderl I am unable to reproduce the described issue with the code below. Can you please confirm that I'm trying to reproduce your issue properly?

Environment:
```
node@8.9.4
winston@2.4.3
winston-daily-rotate-file@3.2.1
```

Test code:

``` javascript
const winston = require('winston');
require('.');

var logger = new (winston.Logger)({
    transports: [
        new (winston.transports.DailyRotateFile)({
            filename: 'application-%DATE%.log'
        })
    ]
});

var error = new Error('Bar');

logger.info('Testing with normal javascript object', {test: 'abc'});
logger.info('Testing with error object', error);

console.log(error);
```

```
matt ~/projects/winstonjs/winston-daily-rotate-file [master *]% node 160-test.js
Bar

matt ~/projects/winstonjs/winston-daily-rotate-file [master *]%
```

The contents of the log file after the above code is:

```
2018-06-20T03:44:41.761Z - info: Testing with normal javascript object test=abc
2018-06-20T03:44:41.763Z - info: Testing with error object Error: Bar
    at Object.<anonymous> (/Users/matt/projects/winstonjs/winston-daily-rotate-file/format-test.js:12:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by mattberther** [comment] 2018-08-16 03:59
Closing due to non-response. If you have further information, please re-open the issue.

**Closed by mattberther** 2018-08-16 03:59 UTC
