### ISSUE TITLE
Window File paths are not valid

### ISSUE THREAD

**Issue by SpudNyk** [winstonjs/winston-daily-rotate-file#139] opened 2018-04-18 20:03 UTC
If I use a file path of C:\Test\testing\test-%DATE%.log log file rotator as of version 3.1.0 counts it as an invalid path

**Comment by mattberther** [comment] 2018-04-18 20:14
This is a dupe of #137 and #138. 

Apologies for the regression. This should be resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/aa3bf83f90057af69e28f43c0a754a5a8283d60e. This has also been pushed to npm as `winston-daily-rotate-file@3.1.2`.

Please re-open if you continue to see issues.

**Closed by mattberther** 2018-04-18 20:14 UTC
