### ISSUE TITLE
TypeError: Class constructor TransportStream cannot be invoked without 'new'

### ISSUE THREAD

**Issue by bouchezb** [winstonjs/winston-daily-rotate-file#154] opened 2018-05-30 08:53 UTC
Hi,

I've updated my npm dependencies this morning and my loggers can't start anymore with `winston-daily-rotate-file@3.2.0` and `winston@3.0.0-rc6`.

I have this error 
```
TypeError: Class constructor TransportStream cannot be invoked without 'new'
at new DailyRotateFile (/home/workspace/node_modules/winston-daily-rotate-file/daily-rotate-file.js:32:15)
```
When i set up my loggers
```
const logger = winston.createLogger({
  level: LOG_LEVEL,
  levels: logLevels.levels,
  format: fileFormat,
  transports: [
    new DailyRotateFile({ filename: path.join(LOGS_DIR, 'error.log'), datePattern: 'YYYY-MM-DD', level: 'error', handleExceptions: true, maxSize: '20m', maxFiles: '2d', zippedArchive: true, datePattern: 'YYYY-MM-DD-HH'}),
    new DailyRotateFile({ filename: path.join(LOGS_DIR, 'silly.log'), datePattern: 'YYYY-MM-DD', level: 'silly', maxSize: '20m', maxFiles: '2d', zippedArchive: true, datePattern: 'YYYY-MM-DD-HH' }),
    new DailyRotateFile({ filename: path.join(LOGS_DIR, 'combined.log'), datePattern: 'YYYY-MM-DD', level: LOG_LEVEL, maxSize: '20m', maxFiles: '2d', zippedArchive: true, datePattern: 'YYYY-MM-DD-HH' })
  ]
});
```
`winston@3.0.0-rc6` needs `winston-transport@^4.0.0` and the error occurs in winston-daily-rotate-file when calling
```
Transport.call(this, options);
```
Looks like there is an issue with winston-transport.
Maybe i'm not setting up thing in the right way, but it was working so far.
My previous version of `winston` was `@next`, so i can't tell what was my real version of winston.
Reproduced on two different machines with Node version `8.9.4` or `9.5.0`

Can you reproduce the issue ?

Regards.

------------------------------------
Edit: searching in my git history and according to publish dates, i think my working version was `winston@3.0.0-rc5` with `winston-transport@^3.1.0`

**Comment by ChrisAlderson** [comment] 2018-05-30 09:30
This is because as of `winston-transport@4.0.0` is using ES6-classes and since `winston-daily-rotate-file` requires `winston-transport` through winston we get this error.

Solution should be to add `winston-transport@3.2.1` as a dependecy in `package.json`.

**Comment by bouchezb** [comment] 2018-05-30 10:26
Hi @ChrisAlderson ,

Thanks for your reply. 

You said: 
> Solution should be to add winston-transport@3.2.1 as a dependecy in package.json.

Do you mean : in `winston@3.0.0`'s `package.json` ?

It was ^3.3.0 since this commit
> https://github.com/winstonjs/winston/commit/1d0a6975669e5deecc384ed55de67c0023b3f6ee#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

You say that `winston-transport@^4.0.0` is using ES6-classes, I understand that `winston-daily-rotate-file@3.2.0` is not already fully compatible with it.
Maybe we need to downgrade `winston@3.0.0` dependencies to `winston-transport@<4.0.0` ?

**Comment by indexzero** [comment] 2018-05-30 11:06
It may be worthwhile to revert Transport back to a prototypal class to avoid inconsistencies in the ecosystem like this.

**Comment by ChrisAlderson** [comment] 2018-05-30 11:17
This inconistenty is the result of not having the correct version of `winston-transport` in the package.json of `winston-daily-rotate-file`,  which is bad since the required version now comes from `winston`. Each custom transport, including daily-rotate-file, should specify their own version of `winston-transport`, so transports can still use `winston-transport@<4.0.0` for prototypes and `winston-transport@>=4.0.0` to use ES6 classes.

**Comment by indexzero** [comment] 2018-05-30 11:27
Not disagreeing with the root cause (which you've correctly identified), just approaching it from another line of reasoning. 

That is, if the change is likely to cause breaks like this because (on average) ecosystem transports don't properly manage their dependencies it is prudent to keep the base Transport in winston-transport backwards compatible.

**Comment by mattberther** [comment] 2018-05-30 14:07
Resolved with https://github.com/winstonjs/winston-daily-rotate-file/commit/f6e809c328432dce2af172dc8e98f998935ca39a and pushed to npm as `winston-daily-rotate-file@3.2.1`.

**Closed by mattberther** 2018-05-30 14:07 UTC

**Comment by bouchezb** [comment] 2018-05-30 15:44
Thanks this fix solved my problem :+1: .
