### ISSUE TITLE
file-stream-rotator@^0.2.1 is missing

### ISSUE THREAD

**Issue by aleybovich** [winstonjs/winston-daily-rotate-file#151] opened 2018-05-22 07:59 UTC
I'm running `npm install winston-daily-rotate-file` and I get the error:

npm ERR! code E404
npm ERR! 404 Not Found: file-stream-rotator@^0.2.1

Reproducible on several machines across the office.

**Comment by ChrisAlderson** [comment] 2018-05-22 08:05
`file-stream-rotator@0.2.1` does exists, [but `npm` is having issues at the moment](https://status.npmjs.org/). So I think this is the issue here.

**Comment by mattberther** [comment] 2018-05-22 21:19
Closing this out as unable to reproduce

**Closed by mattberther** 2018-05-22 21:19 UTC
