### ISSUE TITLE
winston daily rotate does not respect file size limit in multi process environment

### ISSUE THREAD

**Issue by peterbakonyi05** [winstonjs/winston-daily-rotate-file#196] opened 2018-11-13 13:53 UTC
Hi,

I am using` v3.5.1`. When daily rotate is used in a multi process environment (like `pm2` or `iis-node`) and `logRotateFileSizeLimit` is set to `10m`, the actual file size limit will be the `limit` x `number of processes` (80MB in my case).

In my opinion the expected behavior would be that file size does not exceed the specified limit in a multi process environment.

**Comment by mattberther** [comment] 2018-12-19 03:58
Is this related to #197?

**Comment by mattberther** [comment] 2019-01-14 03:07
I'm unable to reproduce this from the description provided. Can you please provide the smallest code example that consistently reproduces the issue?

**Comment by mattberther** [comment] 2019-02-16 20:02
Closing due to non-response. Please reopen if this continues to be an issue.

**Closed by mattberther** 2019-02-16 20:02 UTC
Labels: waiting
