### ISSUE TITLE
how to change value of  "maxSize" after configration

### ISSUE THREAD

**Issue by ankurkapil8** [winstonjs/winston-daily-rotate-file#273] opened 2020-03-21 04:37 UTC
hi,
Below is my code snapshot.

const transports = {
	console: new winston.transports.Console({ //transport for writing logs to console
		level: fileLogsLevel,
		json: false,
		colorize: true,
		silent: false
	}),
	rotateFile: new winston.transports.DailyRotateFile({
		level: fileLogsLevel,
		filename: logsFilePath,
		datePattern: 'YYYY-MM-DD',
		extension:".log",
		zippedArchive: true,
		maxSize: maxFileSize,
		maxFiles: maxNumberOfFiles
	  }),
  };
  const logger = winston.createLogger({
    transports: [
		transports.console,
		transports.file
		]
  });

Now I want to pass the dynamic value of "maxSize" from database table. Please help ASAP.

**Comment by mattberther** [comment] 2020-03-21 15:00
This appears to be a duplicate of https://github.com/winstonjs/winston-daily-rotate-file/issues/228. 

In the event that it is not, accessing a database to populate `maxSize` from a database is outside of the scope of this transport, and I'll leave it to the OP to identify how to retrieve that value given their project requirements.

**Closed by mattberther** 2020-03-21 15:00 UTC
Labels: duplicate
