### ISSUE TITLE
DailyRotateFile doesn't open stream with winston@3.0.0-rc0 when running mocha tests

### ISSUE THREAD

**Issue by cwillwer** [winstonjs/winston-daily-rotate-file#97] opened 2017-10-12 21:12 UTC
When trying to use DailyRotateFile 1.7.2 with winston 3.0.0-rc0 inside of my code that is being exercised by Mocha 4.0.1 tests, it looks like the stream/file isn't getting opened before invoking a write operation on it. Here's the code under test that uses it:

```
require('winston-daily-rotate-file');

const log = winston.createLogger({
  level: 'debug',
  transports: [
    new (winston.transports.Console)({
      colorize: true,
      timestamp: true,
      json: true,
      prettyPrint: true,
    }),
    new (winston.transports.DailyRotateFile)({
      filename: './logs/log.txt',
      localTime: true,
      maxDays: 7,
      createTree: true,
      datePattern: 'yyyy/MM/dd.'
    })
  ]
});

log.debug('output a debug message');
```

The error and call stack is
```
 TypeError: Cannot read property 'write' of undefined
      at module.exports.DailyRotateFile._write (node_modules\winston-daily-rotate-file\index.js:272:25)
      at doWrite (_stream_writable.js:387:12)
      at writeOrBuffer (_stream_writable.js:373:5)
      at module.exports.Writable.write (_stream_writable.js:290:11)
      at DerivedLogger.ondata (_stream_readable.js:642:20)
      at addChunk (_stream_readable.js:266:12)
      at readableAddChunk (_stream_readable.js:253:11)
      at DerivedLogger.Readable.push (_stream_readable.js:211:10)
      at DerivedLogger.Transform.push (_stream_transform.js:147:32)
      at DerivedLogger._transform (node_modules\winston\lib\winston\logger.js:218:8)
      at DerivedLogger.Transform._read (_stream_transform.js:186:10)
      at DerivedLogger.Transform._write (_stream_transform.js:174:12)
      at doWrite (_stream_writable.js:387:12)
      at writeOrBuffer (_stream_writable.js:373:5)
      at DerivedLogger.Writable.write (_stream_writable.js:290:11)
      at DerivedLogger.(anonymous function) [as debug] (node_modules\winston\lib\winston\create-logger.js:45:14)
      at Object.post (src\controllers\accountController.js:9:16435)
      at Context.<anonymous> (tests\accountControllerTests.js:50:25)
```

**Comment by cwillwer** [comment] 2017-10-12 21:16
I should also point out that when I run the app rather than the tests, the console logger (the first transport) outputs the first message, and then no messages ever appear again. I suspect this crash is silently killing the logger.

**Comment by mattberther** [comment] 2017-10-13 16:08
Thanks for the report, @cwillwer. It appears that winston 3.0.0 has introduced some breaking changes. I'll work to get them resolved.

@indexzero Do we have a page describing how non-bundled transports need to be updated?

**Comment by lhviet** [comment] 2017-10-18 07:23
I met exactly the same problem.

**Comment by coussej** [comment] 2017-11-02 11:34
Exactly the same problem here.

**Comment by mike-aungsan** [comment] 2017-11-02 21:45
TypeError: Cannot read property 'write' of undefined
   at module.exports.DailyRotateFile._write (/var/storage/abc/node_modules/winston-daily-rotate-file/index.js:267:25)

**Comment by ridhamtarpara** [comment] 2017-11-05 22:33
same issue with stream

**Comment by mattberther** [comment] 2017-11-05 22:49
Closing this issue as dupe of @#106. Please track the progress of winston 3.0 compatibility there.

**Closed by mattberther** 2017-11-05 22:49 UTC
