### ISSUE TITLE
ENOENT Exception from Daily Rotate File

### ISSUE THREAD

**Issue by rgmembreno** [winstonjs/winston-daily-rotate-file#36] opened 2016-05-02 18:49 UTC
Hello Winston community!

We have been using Winston version 0.7.3 for some time now, and the only major issue that comes up is an occasional ENOENT exception from DailyRotateFile.  It occurs sometime after server startup, and a sample stacktrace is below.  I didn't see any mention of this issue here and on the main Winston repo--we're planning on upgrading to a new version of Winston but we want to know if this problem has been encountered before and corrected after 0.7.3. 

Configuration code:
var fileTransportOpts = {
  filename: './server.log',
  maxsize: 10000000,
  maxFiles: 2,
  json: false,
  handleExceptions: (process.env.NODE_ENV === 'production')
};

var consoleTransportOpts = {
  colorize: true,
  timestamp :true,
  prettyPrint: true
};

var fileTransport = new logger.transports.DailyRotateFile(fileTransportOpts);
var consoleTransport = new logger.transports.Console(consoleTransportOpts);
logger.remove(logger.transports.Console)
.add(logger.transports.Console, consoleTransportOpts)
.add(logger.transports.DailyRotateFile, fileTransportOpts);
expressWinston.requestWhitelist.splice(0, expressWinston.requestWhitelist.length);
expressWinston.requestWhitelist.push('method');
expressWinston.requestWhitelist.push('url');
expressWinston.requestWhitelist.push('query');

var expressWinstonLogger = expressWinston.logger(
  { transports: [fileTransport, consoleTransport]
  , msg: message
  , meta: false
  })

Stack Trace:
016-04-26T21:09:12.754Z - error: uncaughtException: ENOENT, no such file or directory 'server.log.2016-04-26' date=Tue Apr 26 2016 21:09:12 GMT+0000 (UTC), pid=12373, uid=0, gid=0, cwd=/srv/www/<servername>, execPath=/usr/local/bin/node, version=v0.12.7, argv=[/usr/local/bin/node, /srv/www/<servername>/server.js], rss=836734976, heapTotal=640713216, heapUsed=122086896, loadavg=[0.09423828125, 0.10400390625, 0.076171875], uptime=9469895, trace=[column=null, file=null, function=Error, line=null, method=null, native=true, column=18, file=fs.js, function=Object.fs.unlinkSync, line=883, method=fs.unlinkSync, native=false, column=12, file=/srv/www/<servername>/node_modules/winston/lib/winston/transports/daily-rotate-file.js, function=DailyRotateFile._getFile, line=537, method=_getFile, native=false, column=31, file=/srv/www/<servername>/node_modules/winston/lib/winston/transports/daily-rotate-file.js, function=null, line=499, method=null, native=false, column=15, file=fs.js, function=FSReqWrap.oncomplete, line=95, method=oncomplete, native=false], stack=[Error: ENOENT, no such file or directory 'server.log.2016-04-26', at Error (native), at Object.fs.unlinkSync (fs.js:883:18), at DailyRotateFile._getFile (/srv/<servername>/node_modules/winston/lib/winston/transports/daily-rotate-file.js:537:12), at /srv/www/<servername>/node_modules/winston/lib/winston/transports/daily-rotate-file.js:499:31, at FSReqWrap.oncomplete (fs.js:95:15)]

**Comment by mattberther** [comment] 2016-05-06 01:32
Thanks for your report @rgmembreno. Ive encountered this sporadically - but have been unable to reproduce. Id love to get to the bottom of this as well. Do you have consistent steps to reproduce?

**Comment by rgmembreno** [comment] 2016-05-08 22:44
Hi Matt,

To reproduce this issue you need to set the 'maxSize' FileTransportOps property to something really small.  All I had to do was set it to 65 and let my unit tests run and the error will occur.  The error occurs in version 0.8.0 because DailyRotateFile is trying to delete a file that it has already deleted (the original server.log, for example)

**Comment by mattberther** [comment] 2016-05-12 00:12
Thanks @rgmembreno. Im looking at this and will update this ticket as I learn more.

**Comment by rdpoor** [comment] 2016-06-11 11:51
+1.  This is crashing our server as well.  I'm running winston-2.2.0.

**Comment by mattberther** [comment] 2016-06-13 21:17
@rdpoor and @rgmembreno - Im having a tough time coming up with a simple example that reproduces this. Can you create a gist that demonstrates the failure?

Thanks!

**Comment by rdpoor** [comment] 2016-06-14 00:48
@mattberther -- I've poked at it with a desultory stick and have not been able coax it to reproduce in captivity.  At the very least, I'll grab a stack trace next time it happens and see if that offers any insights.

**Comment by mattberther** [comment] 2016-06-14 02:33
Thanks @rdpoor - I've tried running this in a real tight loop and haven't been successful either.

**Comment by rdpoor** [comment] 2016-06-21 14:30
@mattberther -- do check out https://github.com/winstonjs/winston/issues/800 because @nikdunn spells out some theories on the source of the bug.

**Comment by rdpoor** [comment] 2016-06-21 14:31
Here's a tiny bit more info.  I'm running winston 2.1.1 on node 4.4.4 .  In the most recent test, I cleared out the logs directory before running my app -- it ran for about three hours before crashing.

    error: uncaughtException: ENOENT: no such file or directory, open '/Users/r/Projects/microservices/logs/5x00.log' date=Tue Jun 21 2016 01:06:27 GMT-0700 (PDT), pid=82080, uid=503, gid=20, cwd=/Users/r/Projects/microservices, execPath=/usr/local/bin/node, version=v4.4.4, argv=[/usr/local/bin/node, /Users/r/Projects/microservices/server.js], rss=50614272, heapTotal=30141024, heapUsed=24508112, loadavg=[2.43994140625, 2.28564453125, 2.49462890625], uptime=2284126
    Error: ENOENT: no such file or directory, open '/Users/r/Projects/microservices/logs/5x00.log'
    at Error (native)

And the log directory:

    -rw-r--r--   1 r  staff      0 Jun 21 01:06 5x00.log.gz
    -rw-r--r--   1 r  staff   4842 Jun 21 00:43 5x001.log.gz
    -rw-r--r--   1 r  staff   4847 Jun 21 00:20 5x002.log.gz
    -rw-r--r--   1 r  staff   6313 Jun 20 23:33 5x003.log.gz
    -rw-r--r--   1 r  staff   4794 Jun 20 22:02 5x004.log.gz
    -rw-r--r--   1 r  staff  66821 Jun 21 01:06 exception.log
    -rw-r--r--   1 r  staff   2588 Jun 20 23:13 proxy.log

Note that the zero length file has the same write date as the crash.  For reference, here's my config:

```
'use strict';

var winston = require('winston');
var fs      = require('fs');

var logDir  = fs.existsSync('/logs') ? '/logs/' : __dirname + '/../logs/';

module.exports = function(appName) {
  return new (winston.Logger)({
    transports: [
      new winston.transports.Console({
        name                           : 'console',
        colorize                       : true,
        handleExceptions               : true,
        json                           : false,
        humanReadableUnhandledException: true
      }),
      new winston.transports.File({
        filename     : logDir + appName + '.log',
        tailable     : true,
        zippedArchive: true,
        maxsize      : 102400,
        maxFiles     : 30,
        colorize     : true
      })
    ],
    exceptionHandlers: [
      new winston.transports.File({
        filename     : logDir + 'exception.log',
        tailable     : true,
        zippedArchive: true,
        maxsize      : 102400,
        maxFiles     : 30,
        colorize     : true
      })
    ]
  });
};
```

**Comment by md2k** [comment] 2016-07-08 12:03
I can put my 5 cents on the issue, but actually i faced with it while i'm use my application in cluster mode.
Whenever rotation is triggered all processes trying ti unlink same file, so one of processes do it, rest hang with error:
```js
Error: ENOENT, no such file or directory 'logs/xxxxx_server.log.2016-07-08'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:883:18)
    at DailyRotateFile._getFile (/.../node_modules/winston-daily-rotate-file/index.js:584:12)
    at /.../node_modules/winston-daily-rotate-file/index.js:547:31
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Here is my patch, ot perfect, but at least it work as it should and now i not have any issues with rotation
```diff
--- index-orig.js	2016-07-08 10:36:16.906038200 +0200
+++ index.js	2016-07-08 10:38:19.389934888 +0200
@@ -581,9 +581,17 @@
     if (this.maxFiles && (this._created >= (this.maxFiles - 1))) {
       remaining = this._created - (this.maxFiles - 1);
       if (remaining === 0) {
-        fs.unlinkSync(path.join(this.dirname, filename));
+	try {
+	    fs.unlinkSync(path.join(this.dirname, filename));
+	} catch (e) {
+	    console.log(e)
+	}
       } else {
-        fs.unlinkSync(path.join(this.dirname, filename + '.' + remaining));
+	try {
+    	    fs.unlinkSync(path.join(this.dirname, filename + '.' + remaining));
+	} catch (e) {
+	    console.log(e)
+	}
       }
     }
```

**Comment by mattberther** [comment] 2016-07-11 03:10
@md2k thanks for digging into this. could i talk you into submitting a PR for this?

**Comment by mattberther** [comment] 2016-07-11 03:23
@md2k Thanks for your patch. Ive incorporated your change and pushed a new version (1.1.5) to npm. 

Im closing this issue for the DailyRotateFile transport. We should probably continue the conversation on the FileTransport at https://github.com/winstonjs/winston/issues/800.

**Closed by mattberther** 2016-07-11 03:23 UTC
