### ISSUE TITLE
not supprot the version winston 3.0 rc

### ISSUE THREAD

**Issue by koiszzz** [winstonjs/winston-daily-rotate-file#100] opened 2017-10-23 01:46 UTC
When I install the package , the cmd return UNMET PEER DEPENDENCY winston@3.0.0-rc1.
And the example not working with the latest winston.

**Comment by mattberther** [comment] 2017-11-05 22:48
Closing this issue as dupe of @#106. Please track the progress of winston 3.0 compatibility there.

**Closed by mattberther** 2017-11-05 22:48 UTC
