### ISSUE TITLE
NUL US ASCII char

### ISSUE THREAD

**Issue by bletual** [winstonjs/winston-daily-rotate-file#94] opened 2017-10-05 15:03 UTC
When you log a string that contains a NUL character, winston.transports.DailyRotateFile stops to log when option "json" is set to "false".
Example: 

``` javascript
let fileTransport = new winston.transports.DailyRotateFile({
    filename: "/home/project/log",
    datePattern: 'yyyy-MM-dd.',
    prepend: true,
    level: process.env.ENV === 'development' ? 'debug' : 'info',
    maxDays: 31,
    zippedArchive: true,
    json: false
});

let myLogger = new (winston.Logger)({
    transports: [
        fileTransport
    ]
});

myLogger.info("Some String" + "String with a NUL character at the end");
```

Bruno.

PS: with "json" at "true", I think that the json parser take care of it :-)

**Comment by mattberther** [comment] 2017-11-06 06:17
@bletual I'm unable to reproduce this using the logger line below. Do you have a specific string that causes this issue?

``` js
logger.info("Some String" + "String with a NUL character \0at the end\0");
```

**Comment by mattberther** [comment] 2017-11-20 15:09
Closing to non-response.

**Closed by mattberther** 2017-11-20 15:09 UTC
